// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvgmuzcrtvtabfoiqltg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2Z211emNydHZ0YWJmb2lxbHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTExNzMsImV4cCI6MjA2OTQ2NzE3M30.o9aN30u96JHl-JCpxrMiJr4dranawQ52XJOI1DXd-S4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});